name = "rpc-proxy" # todo
main = "./src/index.ts"
compatibility_date = "2022-05-03"
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
routes = [
  { pattern = "r.overhere.gg", custom_domain = true }
]
